
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASTERISK BETWEEN BTREE COMMA CREATE DELETE DROP EQUALS FILE FLOAT FROM HASH ID IN INDEX INDICES INSERT INT INTO K LPAREN N NUMBER POINT RADIUS RPAREN RTREE SELECT SEMICOLON SEQUENTIAL SHOW STR STRING TABLE TABLES VALUES VARCHAR VIEW WHERE WITH\nlista_sentencias : lista_sentencias sentencia SEMICOLON\n\nlista_sentencias : sentencia SEMICOLON\n\nsentencia : CREATE TABLE ID LPAREN lista_columnas RPAREN FROM FILE STRING\n\nsentencia : CREATE TABLE ID LPAREN lista_columnas RPAREN FROM FILE STRING WITH N EQUALS NUMBER\n\nsentencia : CREATE TABLE ID LPAREN lista_columnas RPAREN\n\nsentencia : SHOW TABLES\n\nsentencia : VIEW INDICES FROM ID\n\nsentencia : DROP TABLE ID\n\nsentencia : SELECT ASTERISK FROM ID WHERE ID EQUALS valor\n\nsentencia : SELECT ASTERISK FROM ID WHERE ID BETWEEN valor AND valor\n\nsentencia : SELECT ASTERISK FROM ID WHERE ID IN LPAREN POINT LPAREN valor COMMA valor RPAREN COMMA RADIUS valor RPAREN\n\nsentencia : SELECT ASTERISK FROM ID WHERE ID IN LPAREN POINT LPAREN valor COMMA valor RPAREN COMMA K valor RPAREN\n\nsentencia : INSERT INTO ID VALUES LPAREN lista_valores RPAREN\n\nlista_valores : lista_valores COMMA valor\n\nlista_valores : valor\n\nsentencia : DELETE FROM ID WHERE ID EQUALS valor\n\nvalor : STRING\n      | NUMBER  \n\ncolumna : ID tipo_dato INDEX tecnica_indice LPAREN ID COMMA ID RPAREN\n\ncolumna : ID tipo_dato INDEX tecnica_indice\n\ncolumna : ID tipo_dato\n\nlista_columnas : lista_columnas COMMA columna\n\nlista_columnas : columna\n\ntipo_dato : INT\n          | FLOAT\n          | VARCHAR\n          | STR\n\ntecnica_indice : BTREE\n               | RTREE\n               | HASH\n               | SEQUENTIAL\n'
    
_lr_action_items = {'CREATE':([0,1,11,19,],[3,3,-2,-1,]),'SHOW':([0,1,11,19,],[4,4,-2,-1,]),'VIEW':([0,1,11,19,],[5,5,-2,-1,]),'DROP':([0,1,11,19,],[6,6,-2,-1,]),'SELECT':([0,1,11,19,],[7,7,-2,-1,]),'INSERT':([0,1,11,19,],[8,8,-2,-1,]),'DELETE':([0,1,11,19,],[9,9,-2,-1,]),'$end':([1,11,19,],[0,-2,-1,]),'SEMICOLON':([2,10,13,22,27,42,47,48,56,58,65,70,75,84,92,93,],[11,19,-6,-8,-7,-5,-17,-18,-13,-16,-9,-3,-10,-4,-11,-12,]),'TABLE':([3,6,],[12,15,]),'TABLES':([4,],[13,]),'INDICES':([5,],[14,]),'ASTERISK':([7,],[16,]),'INTO':([8,],[17,]),'FROM':([9,14,16,42,],[18,21,23,51,]),'ID':([12,15,17,18,21,23,26,30,34,43,69,77,],[20,22,24,25,27,28,31,36,44,31,73,80,]),'LPAREN':([20,29,55,59,60,61,62,63,72,],[26,35,67,69,-28,-29,-30,-31,76,]),'VALUES':([24,],[29,]),'WHERE':([25,28,],[30,34,]),'INT':([31,],[38,]),'FLOAT':([31,],[39,]),'VARCHAR':([31,],[40,]),'STR':([31,],[41,]),'RPAREN':([32,33,37,38,39,40,41,45,46,47,48,52,59,60,61,62,63,68,80,83,85,90,91,],[42,-23,-21,-24,-25,-26,-27,56,-15,-17,-18,-22,-20,-28,-29,-30,-31,-14,83,-19,86,92,93,]),'COMMA':([32,33,37,38,39,40,41,45,46,47,48,52,59,60,61,62,63,68,73,79,83,86,],[43,-23,-21,-24,-25,-26,-27,57,-15,-17,-18,-22,-20,-28,-29,-30,-31,-14,77,82,-19,87,]),'STRING':([35,49,53,54,57,64,71,76,82,88,89,],[47,47,47,47,47,70,47,47,47,47,47,]),'NUMBER':([35,49,53,54,57,71,76,81,82,88,89,],[48,48,48,48,48,48,48,84,48,48,48,]),'EQUALS':([36,44,78,],[49,53,81,]),'INDEX':([37,38,39,40,41,],[50,-24,-25,-26,-27,]),'BETWEEN':([44,],[54,]),'IN':([44,],[55,]),'AND':([47,48,66,],[-17,-18,71,]),'BTREE':([50,],[60,]),'RTREE':([50,],[61,]),'HASH':([50,],[62,]),'SEQUENTIAL':([50,],[63,]),'FILE':([51,],[64,]),'POINT':([67,],[72,]),'WITH':([70,],[74,]),'N':([74,],[78,]),'RADIUS':([87,],[88,]),'K':([87,],[89,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'lista_sentencias':([0,],[1,]),'sentencia':([0,1,],[2,10,]),'lista_columnas':([26,],[32,]),'columna':([26,43,],[33,52,]),'tipo_dato':([31,],[37,]),'lista_valores':([35,],[45,]),'valor':([35,49,53,54,57,71,76,82,88,89,],[46,58,65,66,68,75,79,85,90,91,]),'tecnica_indice':([50,],[59,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> lista_sentencias","S'",1,None,None,None),
  ('lista_sentencias -> lista_sentencias sentencia SEMICOLON','lista_sentencias',3,'p_lista_sentencias_varias','sql_parser.py',81),
  ('lista_sentencias -> sentencia SEMICOLON','lista_sentencias',2,'p_lista_sentencias_una','sql_parser.py',88),
  ('sentencia -> CREATE TABLE ID LPAREN lista_columnas RPAREN FROM FILE STRING','sentencia',9,'p_sentencia_create_file_archivos','sql_parser.py',94),
  ('sentencia -> CREATE TABLE ID LPAREN lista_columnas RPAREN FROM FILE STRING WITH N EQUALS NUMBER','sentencia',13,'p_sentencia_create_file_con_n','sql_parser.py',108),
  ('sentencia -> CREATE TABLE ID LPAREN lista_columnas RPAREN','sentencia',6,'p_sentencia_create_file_sin_archivos','sql_parser.py',122),
  ('sentencia -> SHOW TABLES','sentencia',2,'p_sentencia_show_tables','sql_parser.py',132),
  ('sentencia -> VIEW INDICES FROM ID','sentencia',4,'p_sentencia_view_indices','sql_parser.py',138),
  ('sentencia -> DROP TABLE ID','sentencia',3,'p_sentencia_drop_table','sql_parser.py',147),
  ('sentencia -> SELECT ASTERISK FROM ID WHERE ID EQUALS valor','sentencia',8,'p_sentencia_select_asterisco_igualdad','sql_parser.py',157),
  ('sentencia -> SELECT ASTERISK FROM ID WHERE ID BETWEEN valor AND valor','sentencia',10,'p_sentencia_select_asterisco_rango','sql_parser.py',174),
  ('sentencia -> SELECT ASTERISK FROM ID WHERE ID IN LPAREN POINT LPAREN valor COMMA valor RPAREN COMMA RADIUS valor RPAREN','sentencia',18,'p_sentencia_select_espacial_radio','sql_parser.py',190),
  ('sentencia -> SELECT ASTERISK FROM ID WHERE ID IN LPAREN POINT LPAREN valor COMMA valor RPAREN COMMA K valor RPAREN','sentencia',18,'p_sentencia_select_espacial_knn','sql_parser.py',210),
  ('sentencia -> INSERT INTO ID VALUES LPAREN lista_valores RPAREN','sentencia',7,'p_sentencia_insert','sql_parser.py',229),
  ('lista_valores -> lista_valores COMMA valor','lista_valores',3,'p_lista_valores_varios','sql_parser.py',241),
  ('lista_valores -> valor','lista_valores',1,'p_lista_valores_uno','sql_parser.py',247),
  ('sentencia -> DELETE FROM ID WHERE ID EQUALS valor','sentencia',7,'p_sentencia_delete','sql_parser.py',254),
  ('valor -> STRING','valor',1,'p_valor','sql_parser.py',269),
  ('valor -> NUMBER','valor',1,'p_valor','sql_parser.py',270),
  ('columna -> ID tipo_dato INDEX tecnica_indice LPAREN ID COMMA ID RPAREN','columna',9,'p_columna_con_indice_compuesto','sql_parser.py',280),
  ('columna -> ID tipo_dato INDEX tecnica_indice','columna',4,'p_columna_con_indice','sql_parser.py',291),
  ('columna -> ID tipo_dato','columna',2,'p_columna_sin_indice','sql_parser.py',298),
  ('lista_columnas -> lista_columnas COMMA columna','lista_columnas',3,'p_lista_columnas_varias','sql_parser.py',308),
  ('lista_columnas -> columna','lista_columnas',1,'p_lista_columnas_una','sql_parser.py',316),
  ('tipo_dato -> INT','tipo_dato',1,'p_tipo_dato','sql_parser.py',325),
  ('tipo_dato -> FLOAT','tipo_dato',1,'p_tipo_dato','sql_parser.py',326),
  ('tipo_dato -> VARCHAR','tipo_dato',1,'p_tipo_dato','sql_parser.py',327),
  ('tipo_dato -> STR','tipo_dato',1,'p_tipo_dato','sql_parser.py',328),
  ('tecnica_indice -> BTREE','tecnica_indice',1,'p_tecnica_indice','sql_parser.py',335),
  ('tecnica_indice -> RTREE','tecnica_indice',1,'p_tecnica_indice','sql_parser.py',336),
  ('tecnica_indice -> HASH','tecnica_indice',1,'p_tecnica_indice','sql_parser.py',337),
  ('tecnica_indice -> SEQUENTIAL','tecnica_indice',1,'p_tecnica_indice','sql_parser.py',338),
]
